feat: add feature nat module
orange-cloudavenue/terraform-cloudavenue-nats pull request #2
Opened 2023-11-08 15:32 UTC by llewita

2023-11-20 14:22 UTC, azrod requested changes
Add result of unit test

2023-11-20 14:22 UTC, azrod commented on .terraform-docs.yml
> +  show-all: true  # deprecated in v0.13.0, removed in v0.15.0
Actual version of terraform-docs is v0.16.0

2023-11-20 14:22 UTC, azrod commented on main.tf
> +resource "cloudavenue_edgegateway_nat_rule" "example" {
```suggestion
resource "cloudavenue_edgegateway_nat_rule" "nat-rule" {
```

2023-11-20 14:22 UTC, azrod commented on tests/setup/main.tf
> +  name                  = "ModuleTF"
Randomize name

2023-11-20 14:22 UTC, azrod commented on tests/setup/main.tf
> +      "description"               = "description DNAT example Updated!!"
```suggestion
      "description"               = "description DNAT example"
```

2023-11-21 14:02 UTC, llewita commented
Example of success running test:
```
terraform test
tests\nat.tftest.hcl... in progress
  run "setup_tests"... pass
tests\nat.tftest.hcl... tearing down
tests\nat.tftest.hcl... pass

Success! 1 passed, 0 failed.
```

2023-11-22 13:02 UTC, azrod approved these changes

2023-11-22 13:33 UTC, merged